Update build.yml

diff --git a/build.yml b/build.yml
--- a/build.yml
+++ b/build.yml
@@ -5,8 +5,23 @@ phases:
     runtime-versions:
       nodejs: 18
     commands:
-      - npm install
-      - zip -r TEST_NODE.zip *
+      - retry_count=0
+        max_retries=3
+        while [ $retry_count -lt $max_retries ]; do
+          npm install
+          result=$?
+          if [ $result -eq 0 ]; then
+            echo "Dependencies installation successful."
+            break
+          else
+            let "retry_count=retry_count+1"
+            echo "Attempt $retry_count/$max_retries failed. Retrying..."
+          fi
+          if [ $retry_count -eq $max_retries ]; then
+            echo "All installation attempts failed."
+            exit 1
+          fi
+        done
   post_build:
     commands:
       - aws s3 cp TEST_NODE.zip s3://lambda-codebuild-sources/
